name: Build all targets
permissions:
  contents: read

on:
  push:

jobs:
  build_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build build-essential llvm

      - name: Setup GCC 14
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 14

      - name: Make config script executable
        run: chmod +x ./configure-cmake.sh

      - name: Run build
        id: build_run
        run: ./configure-cmake.sh && cmake --build build
        shell: bash
        env:
          CXX: g++-14
          CC: gcc-14
