name: Test Coverage

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y cmake ninja-build build-essential nasm lcov

      - name: Setup GCC 14
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 14

      - name: Configure with coverage flags
        run: cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=ON .

      - name: Build
        run: cmake --build build
        env:
          CXX: g++-14
          CC: gcc-14

      - name: Run tests
        run: cd build && ctest --output-on-failure

      - name: Capture and generate coverage
        run: |
          cd build
          lcov --capture --directory . --output-file coverage.info --ignore-errors mismatch
          lcov --remove coverage.info '/usr/*' '*/_deps/*' --output-file coverage.info
          genhtml coverage.info --output-directory coverage_html --ignore-errors source


      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/coverage.info
          flags: unittests
          name: codecov-neutronium

