name: Run tests (GCC)
permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build build-essential

      - name: Setup GCC 15
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 15

      - name: Make config script executable
        run: chmod +x ./configure-cmake.sh

      - name: Run build
        id: build_run
        run: ./configure-cmake.sh && cmake --build build
        shell: bash
        env:
          CXX: g++-15
          CC: gcc-15

      - name: Run tests
        run: cd build && ctest --output-on-failure
