name: Run Tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build build-essential nasm


      - name: Make build script executable
        run: chmod +x ./cmake-build.sh

      - name: Run build
        id: build_run
        run: ./cmake-build.sh
        shell: bash

      - name: Run tests
        run: cd build && ctest --output-on-failure
